### ISSUE TITLE
Custom Transpiler Stage Plugin (layout) not showing

### ISSUE THREAD

**Issue by iyanmv** [Qiskit/qiskit#12615]
### Environment

- **Qiskit version**: 1.1.0
- **Python version**: 3.11.8

### What is happening?

I tried to create a custom layout plugin following [this documentation](https://docs.quantum.ibm.com/transpile/create-a-transpiler-plugin). My custom layout did not appear when executing `list_stage_plugins("layout")` so I tried to to use the exact same example provided in the documentation. I created a python package, a pyproject.toml, etc. I install the new package without issues, but the plugin is still not listed with `list_stage_plugins("layout")`.

This is the structure of my package:

```
pyproject.toml
src/
   qiskit_custom_layout
      __init__.py
      custom_layout_plugin.py
```

In the module `custom_layout_plugin.py` I copy-paste the example from the docs. And this is my `pyproject.toml`:

```toml
[project]
name = "qiskit-custom-layout"
version = "0.1.0"
description = "A transpiler stage plugin that implements a custom layout"
authors = [
    {name = "Iyán Méndez Veiga", email = "me@iyanmv.com"},
]
dependencies = [
    "qiskit>=1.0.0",
    "gmpy2>=2.1.5",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.entry-points."qiskit.transpiler.layout"]
custom_layout = "custom_layout_plugin:VF2LayoutPlugin"
```

I tried both with `custom_layout` and `"custom_layout"` as in the Qiskit docs the entry point variable is done with quotes but in the setuptools docs is always without, but it doesn't make a difference.

Am I doing something wrong?

### How can we reproduce the issue?

Try to create a custom plugin exactly as described in the documentation.

### What should happen?

Custom layout plugin should appear.
